/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation
 
 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Hadiths',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'hadiths',
        },
      ],
    },
    {
      type: 'category',
      label: 'Stories of Sahaba',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'sahaba-stories',
        },
      ],
    },
    {
      type: 'category',
      label: 'Sunnats',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'sunnats',
        },
      ],
    },
    {
      type: 'category',
      label: 'Duas',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'duas',
        },
      ],
    },
    {
      type: 'category',
      label: 'Islamic Knowledge',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'islamic-knowledge',
        },
      ],
    },
    'contributing',
  ],
};

module.exports = sidebars;

